# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Trappist.AgentCat
PackageVersion: 26.40.0
InstallerLocale: en-US
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/yong076/agent-cat-releases/releases/download/v26.40.0/AgentCat-26.40.0-windows-x64-setup.exe
    InstallerSha256: 94CAB0AE3D0562C683C1B3EEC1DD1C18986BA6602689A85FAF56BC21924AE8D9
    ProductCode: Agent Cat
    AppsAndFeaturesEntries:
      - DisplayName: Agent Cat
        Publisher: trappist
        ProductCode: Agent Cat
        InstallerType: nullsoft
ManifestType: installer
ManifestVersion: 1.6.0
